# Generated by Django 4.1.4 on 2022-12-27 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('square_type', models.CharField(choices=[('EMT', 'empty'), ('BOT', 'robot'), ('BUG', 'bug')], default='EMT', max_length=3)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
    ]
