# Generated by Django 4.1.4 on 2022-12-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='square',
            name='square_type',
            field=models.CharField(blank=True, choices=[('EMT', 'empty'), ('BOT', 'robot'), ('BUG', 'bug')], default='EMT', max_length=3),
        ),
    ]
