# Generated by Django 4.1.4 on 2022-12-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0002_alter_square_square_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='square',
            name='square_type',
            field=models.CharField(choices=[('EMT', 'empty'), ('BOT', 'robot'), ('BUG', 'bug')], default='EMT', max_length=3),
        ),
    ]
