# Generated by Django 4.1.4 on 2022-12-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('robot_strength', models.IntegerField()),
            ],
        ),
    ]
